name: Demo Project

on:
  push:
    branches:
      - master
      - release-*
  pull_request:
    paths:
      - "**.cs"
      - "**.csproj"
      - "**/demo.yml"

permissions:
  contents: read

jobs:
  build:

    name: Demo Project (${{ matrix.os }}, ${{ matrix.browser }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, macos-latest]
        browser: [chrome, firefox]
    env:
      DOTNET_VERSION: '10.0.x' # The .NET SDK version to use

    steps:
    - name: Harden the runner
      uses: step-security/harden-runner@351661ca32ac09a36dc5ee2d536e3128f2a3c8ed # v2.22.0
      with:
        use-policy-store: true
        api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

    - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
    - uses: actions/setup-dotnet@871f041373faaad213a635d9afb62905ec029bbb # v1.10.1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Setup NuGet
      uses: step-security/setup-nuget@b53c6b9c5a37611f049ad5ebbbd184d01ff97009 # v4.0.1

    - name: Install dependencies
      working-directory: ./demos/PuppeteerSharpPdfDemo
      run: |
        dotnet restore PuppeteerSharpPdfDemo-Local.csproj
    - name: Run on .NET
      working-directory: ./demos/PuppeteerSharpPdfDemo
      run: |
          dotnet run --project PuppeteerSharpPdfDemo-Local.csproj auto-exit ${{ matrix.browser }} -f net10.0
    - name: Run with AOT
      if: matrix.os == 'windows-2022'
      working-directory: ./demos/PuppeteerSharpPdfDemo
      run: |
          dotnet publish PuppeteerSharpPdfDemo-Local.csproj -r win-x64 -o build -f net10.0
          build/PuppeteerSharpPdfDemo-Local.exe auto-exit ${{ matrix.browser }}
    - name: Run on .NET Framework
      if: matrix.os == 'windows-2022'
      continue-on-error: ${{ matrix.browser == 'firefox' }}
      working-directory: ./demos/PuppeteerSharpPdfDemo
      run: |
          dotnet run --project PuppeteerSharpPdfDemo-Local.csproj auto-exit ${{ matrix.browser }} -f net481
