name: WebDriverBiDi leak check

on:
  push:
    branches:
      - master
      - release-*
  pull_request:
    paths:
      - "**.cs"
      - "**.csproj"
      - "**/leak-check.yml"

permissions:
  contents: read

jobs:
  build:
    name: WebDriverBiDi leak check
    runs-on: ubuntu-latest
    env:
      DOTNET_VERSION: "10.0.x" # The .NET SDK version to use

    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@351661ca32ac09a36dc5ee2d536e3128f2a3c8ed # v2.22.0
        with:
          use-policy-store: true
          api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      - uses: actions/setup-dotnet@871f041373faaad213a635d9afb62905ec029bbb # v1.10.1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Install dependencies
        run: |
          dotnet restore lib/PuppeteerSharp.sln
      - name: Build (CDP only)
        run: |
          dotnet build lib/PuppeteerSharp/PuppeteerSharp.csproj /p:DefineConstants=CDP_ONLY --configuration Release --no-restore
          ls ./lib/PuppeteerSharp/bin/Release
      - name: Check for WebDriverBiDi leakage (CDP only)
        run: |
          dotnet tools/csharp/check-leaks.cs ./lib/PuppeteerSharp/bin/Release
