name: Publish docs

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:

    name: Publish docs
    runs-on: windows-latest
    env:
      DOTNET_VERSION: '10.0.x' # The .NET SDK version to use

    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@351661ca32ac09a36dc5ee2d536e3128f2a3c8ed # v2.22.0
        with:
          use-policy-store: true
          api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@55ec9447dda3d1cf6bd587150f3262f30ee10815 # v3.4.2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Build
        run: |
          dotnet tool install --global docfx --version 2.74.1

          docfx metadata docfx_project\docfx.json
          docfx build docfx_project\docfx.json -o docs
      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0
      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: 'docs'
      - name: Publish Documentation on GitHub Pages
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
        id: deployment
      - name: Upload Site to artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: 'Website'
          path: docs/
          retention-days: 1
          if-no-files-found: ignore
        if: always()
        continue-on-error: true
